name: CI

on: [push]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@master
   - uses: actions/setup-python@v2
     with:
       python-version: '3.x' # Version range or exact version of a Python version to use, using semvers version range syntax.
       architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
   - run: |
       pip install mkdocs
       pip install mkdocs-material
       cd docs
       mkdocs gh-deploy
